### ISSUE TITLE
运行报错误，每个脚本都是

### ISSUE THREAD

**Issue by cisco6005** [shuye73/MyActions#10]
Run node onlyOneExecute.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'axios'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/runner/work/OK/OK/onlyOneExecute.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Error: Process completed with exit code 1.

**Comment by shuye73** [comment]
在修

**Comment by shuye73** [comment]
已修复

**Comment by cisco6005** [comment]
> 已修复
OK，已经正常。
