### ISSUE TITLE
粉丝互动错误

### ISSUE THREAD

**Issue by kanvenzeng** [shuye73/MyActions#39]
能修复一下吗？

TypeError: resp.headers.set-cookie is not iterable
    at $.get (/jd/scripts/jd_fanslove.js:395:43)
    at isSurge.isLoon.isQuanX.isNode.got.on.then.t (/jd/scripts/jd_f                                                                              anslove.js:512:5618)
    at process._tickCallback (internal/process/next_tick.js:68:7)

❗️粉丝互动, 错误!
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at $.post (/jd/scripts/jd_fanslove.js:289:23)
    at got.post.then.t (/jd/scripts/jd_fanslove.js:512:6689)
    at process._tickCallback (internal/process/next_tick.js:68:7)

❗️粉丝互动, 错误!
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at $.post (/jd/scripts/jd_fanslove.js:268:23)
    at got.post.then.t (/jd/scripts/jd_fanslove.js:512:6689)
    at process._tickCallback (internal/process/next_tick.js:68:7)

❗️粉丝互动, 错误!
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at $.post (/jd/scripts/jd_fanslove.js:244:23)
    at got.post.then.t (/jd/scripts/jd_fanslove.js:512:6689)
    at process._tickCallback (internal/process/next_tick.js:68:7)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at safeGet (/jd/scripts/jd_fanslove.js:502:21)
    at $.post (/jd/scripts/jd_fanslove.js:126:15)
    at got.post.then.t (/jd/scripts/jd_fanslove.js:512:6689)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by shuye73** [comment]
修不了 这脚本一直都是这样 最近打算把这个还有百变大咖秀撤除，没看到多少收益
